variables:
  KANIKO_VERSION: 0.7.0

  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"

stages:
  - build
  - test

build:
  stage: build
  image:
    name: "gcr.io/kaniko-project/executor:debug-v$KANIKO_VERSION"
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --build-arg "KANIKO_TAG=debug-v$KANIKO_VERSION"
      --context "$CI_PROJECT_DIR"
      --destination "$BUILD_IMAGE_NAME"

test:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  script:
    - /build/build.sh --no-push --cache=false
