variables:
  DOCKER_DRIVER: overlay2

  BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
  RELEASE_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:stable"

  CI_APPLICATION_TAG: "$CI_COMMIT_SHA"
  CI_APPLICATION_REPOSITORY: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/$CI_JOB_NAME"

services:
  - docker:stable-dind

stages:
  - build
  - test
  - test-run
  - release

build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --tag "$BUILD_IMAGE_NAME" .
    - docker push "$BUILD_IMAGE_NAME"

test-shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck src/build.sh

test-dockerfile:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  script:
    - cd "$CI_PROJECT_DIR/test/ruby_with_dockerfile"
    - /build/build.sh

# This test is to prevent a regression until https://github.com/docker/engine/pull/339 is out
# See https://gitlab.com/gitlab-org/cluster-integration/auto-build-image/issues/13 for context
test-redhat-registry:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  script:
    - cd "$CI_PROJECT_DIR/test/redhat_registry"
    - /build/build.sh

test-herokuish:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  script:
    - cd "$CI_PROJECT_DIR/test/ruby"
    - /build/build.sh

test-run-herokuish:
  stage: test-run
  image: docker:stable
  needs: ["test-herokuish"]
  services:
    - name: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/test-herokuish:$CI_APPLICATION_TAG"
      alias: app
  script:
    - wget app:5000
    - grep 'Hello World!' index.html

test-herokuish-with-build-secrets:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  variables:
    FORWARDED_VARIABLE_0: 'my forwarded variable 0'
    FORWARDED_VARIABLE_1: 'my forwarded variable 1'
    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: FORWARDED_VARIABLE_0,FORWARDED_VARIABLE_1
  script:
    - cd "$CI_PROJECT_DIR/test/ruby"
    - /build/build.sh

test-herokuish-with-buildpack-url:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  variables:
    BUILDPACK_URL: https://github.com/HashNuke/heroku-buildpack-elixir.git
  script:
    - cd "$CI_PROJECT_DIR/test/elixir"
    - /build/build.sh

test-rspec:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  before_script:
    - gem install --no-rdoc --no-ri bundler
    - bundle install --without rubocop
  script:
    - bundle exec rspec

test-rubocop:
  stage: test
  image: ruby:2.5
  before_script:
    - gem install bundler
    - bundle install --without test
  script:
    - bundle exec rubocop Gemfile src spec

release:
  stage: release
  image: docker:stable
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull "$BUILD_IMAGE_NAME"
    - docker tag "$BUILD_IMAGE_NAME" "$RELEASE_IMAGE_NAME"
    - docker push "$RELEASE_IMAGE_NAME"
