test-run-herokuish:
  stage: test-run
  needs: ["test-herokuish"]
  services:
    - name: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/test-herokuish:$CI_APPLICATION_TAG"
      alias: app
  script:
    - wget app:5000
    - grep 'Hello World!' index.html

test-run-cnb:
  stage: test-run
  needs: ["test-cnb"]
  variables:
    AUTO_DEVOPS_BUILD_IMAGE_CNB_ENABLED: "true"
  services:
    - name: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG/test-cnb:$CI_APPLICATION_TAG"
      alias: app
  script:
    - wget app:5000
    - grep 'Hello World!' index.html
